package com.example.calcolocodicefiscale.utils;
// Generated 5-gen-2017 18.09.54 by Hibernate Tools 5.2.0.CR1


/**
 * Comuni generated by hbm2java
 */

public class Comuni implements java.io.Serializable {

	private String codice;
	private String descrizione;
	private String cap;
	private String codBelfiore;
	private String provincia;
	private Integer pit;


	public Comuni() {
	}

	public Comuni(String codice) {
		this.codice = codice;
	}



	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	
	public String getCap() {
		return this.cap;
	}

	public void setCap(String cap) {
		this.cap = cap;
	}

	public String getCodBelfiore() {
		return this.codBelfiore;
	}

	public void setCodBelfiore(String codBelfiore) {
		this.codBelfiore = codBelfiore;
	}

	
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	
	public Integer getPit() {
		return this.pit;
	}



	@Override
	public String toString(){
		return descrizione+" ("+provincia+")";
	}
	


	public void setPit(Integer pit) {
		this.pit = pit;
	}
	
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codice == null) ? 0 : codice.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Comuni other = (Comuni) obj;
		if (codice == null) {
			if (other.codice != null)
				return false;
		} else if (!codice.equals(other.codice))
			return false;
		return true;
	}


}
